// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbslbsvtmvzmhrojsdqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtic2xic3Z0bXZ6bWhyb2pzZHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDkxMDYsImV4cCI6MjA3MTIyNTEwNn0.7XpbHWsJdonmHaNBDVSMBCchyQOIO4SJWpF79Xr9vT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});